/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef Arcanum_Engine_hpp
#define Arcanum_Engine_hpp

#include <Pollux/Graphics/Canvas.hpp>
#include <Arcanum/Game/Settings.hpp>
#include <Arcanum/Managers/SpriteManager.hpp>
#include <Pollux/Events/EventHandler.hpp>
#include <Arcanum/UI/MainMenu.hpp>
#include <Pollux/Events/Handler.hpp>
#include <Pollux/Time/FpsCounter.hpp>
#include <Pollux/Common/IntToChars.hpp>
#include <Pollux/Managers/TextureManager.hpp>
#include <Arcanum/Creators/ObjectCreator.hpp>
#include <Arcanum/Objects/Location.hpp>
#include <Arcanum/Formats/DatLoader.hpp>
#include <Arcanum/Formats/DatReader.hpp>

namespace Arcanum
{
	class Engine
	{
	public:
		Engine(Settings& settings);
		~Engine();
		void Run();
	private:
		ObjectCreator          _ObjectCreator;
		Pollux::IntToChars     _IntToChars;
		Pollux::FpsCounter     _FpsCounter;
		Pollux::Color          _ColorKey;
		Settings&              _Settings;
		Pollux::Canvas         _Canvas;
		Pollux::EventHandler   _EventHandler;
		Pollux::FileLoader     _FileLoader;
		FileManager            _FileManager;
		Pollux::ImageLoader    _ImageLoader;
		Pollux::TextureManager _TextureManager;
		SpriteManager          _SpriteManager;
		MainMenu               _MainMenu;
		Pollux::Handler        _Handler;
		Location               _Location;
	};
}

#endif 
