/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef Pollux_Graphics_Canvas_hpp
#define Pollux_Graphics_Canvas_hpp

#include <SDL.h>
#include <Pollux/Containers/String.hpp>
#include <Pollux/Graphics/Canvas.hpp>
#include <Pollux/Graphics/Point.hpp>
#include <Pollux/Events/Event.hpp>
#include <Pollux/Graphics/Color.hpp>

namespace Pollux
{
	class Texture;

	class Canvas
	{
	public:
		Canvas(const Point& size, const String& title);
		~Canvas();
		void Title(const String& title);
		const Point& Size() const;
		void Fill(const Point& pos, const Point& size, const Color& color) const;
		void Present();
		void Draw(const Texture* texture, const Point& dstPos, const Point& dstSize, const Point& srcPos, const Point& srcSize);
		void Draw(const Texture* texture, const Point& dstPos);
		SDL_Renderer* GetRenderImpl();
	private:
		SDL_Window*   _Window;
		SDL_Renderer* _Render;
		Point         _Size;
	};
}

#endif
