/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef Arcanum_Formats_Art_hpp
#define Arcanum_Formats_Art_hpp

#include <cstdint>

namespace Arcanum
{
	struct ArtColor
	{
		uint8_t b = 0;
		uint8_t	g = 0;
		uint8_t	r = 0;
		uint8_t	a = 0;
	};

	struct ArtTable
	{
		ArtColor colors[256] = { 0 };
	};

	struct ArtHeader
	{
		uint32_t h0[3]            = { 0 };
		ArtColor stupid_color[4]  = { 0 };

		uint32_t frame_num_low    = 0;
		uint32_t frame_num        = 0;

		ArtColor palette_data1[8] = { 0 };
		ArtColor palette_data2[8] = { 0 };
		ArtColor palette_data3[8] = { 0 };
	};

	struct ArtFrameHeader
	{
		uint32_t width  = 0;
		uint32_t height = 0;
		uint32_t size   = 0;
		int c_x         = 0;
		int c_y         = 0;
		int d_x         = 0;
		int d_y         = 0;
	};
}

#endif 